### ISSUE TITLE
Help with setting up basic project.

### ISSUE THREAD

**Issue by Garney0** [kapi2289/vulcan-api#73]
Hi! I am new to github/asyncio stuff so I'd love to see some help!
My problem is that I want to create simple application using API. Nothing fancy at all, just connect API and display for example name of student. I tried to set it up using documentation but I failed at registering account. My whole code is
```py
import json
import asyncio
from vulcan import Vulcan
from vulcan import Account
from vulcan import VulcanHebe
from vulcan import Keystore
        
async def main():
    keystore = Keystore.create()
    with open("keystore.json", "w") as f:
        # write a formatted JSON representation
        f.write(keystore.as_json)
    account = Account.register(keystore, "xxx", "xxx", "xxx")
    with open("account.json", "w") as f:
        # write a formatted JSON representation
        f.write(account.as_json)

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
and log says:
```
Generating key pair...
Getting Firebase token...
Generated for Vulcan API (Python 3.8.6), sha1: x
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\main.py", line 20, in <module>
    loop.run_until_complete(main())
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\Users\PC\Desktop\main.py", line 16, in main
    f.write(account.as_json)
AttributeError: 'coroutine' object has no attribute 'as_json'
sys:1: RuntimeWarning: coroutine 'Account.register' was never awaited
```
I have no idea why(keystore is generating correctly I am pretty sure), and help would be greatly appreciated!

**Comment by Garney0** [comment]
Okay I think I've managed to successfully register account by adding await. Now my problem is that I can't select student.
```py
client = VulcanHebe(keystore, account)
    await client.select_student()
    print(client.student.full_name)
```
I am reading keystore and account variables from json file and it throws me this message:
```
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\main.py", line 34, in <module>
    loop.run_until_complete(main())
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\Users\PC\Desktop\main.py", line 28, in main
    await client.select_student()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\vulcan\hebe\_hebe_client.py", line 42, in select_student
    students = await self.get_students()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\vulcan\hebe\_hebe_client.py", line 61, in get_students
    self._students = await Student.get(self._api)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\vulcan\hebe\model\_student.py", line 75, in get
    data = await api.get(STUDENT_LIST, **kwargs)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\vulcan\hebe\_api.py", line 139, in get
    return await self._request("GET", url, body=None, **kwargs)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\vulcan\hebe\_api.py", line 101, in _request
    if self._rest_url
AttributeError: 'Api' object has no attribute '_rest_url'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021170090CA0>
```

**Comment by kuba2k2** [comment]
Apparently, the `Account` you're passing to the constructor is either `None` or doesn't contain valid data. Please post the account.json file content (you can hide your e-mail) and the code responsible for reading the file.

**Comment by Garney0** [comment]
> Apparently, the `Account` you're passing to the constructor is either `None` or doesn't contain valid data. Please post the account.json file content (you can hide your e-mail) and the code responsible for reading the file.

contents:
```
{
    "LoginId": 3961,
    "RestURL": "https://lekcjaplus.vulcan.net.pl/powiatx/",
    "UserLogin": "email",
    "UserName": "email"
}
```
code (from documentation):
```py
    with open("keystore.json") as f:
        # load from a file-like object
        keystore = Keystore.load(f)
        # load from a JSON string
        keystore = Keystore.load(f.read())

    with open("account.json") as f:
        # load from a file-like object
        account = Account.load(f)
        # load from a JSON string
        account = Account.load(f.read())
```

**Comment by kuba2k2** [comment]
Uhm, okay. This probably needs more clarification in the docs, but you can not use both account loading methods - just choose between `Account.load(f)` and `Account.load(f.read())`. This is provided just to illustrate all possibilities of loading an object (not only from a file), but you can't use both at once.

**Comment by Garney0** [comment]
Ooooh lol, I really thought I got rid of one of them

**Comment by Garney0** [comment]
Yep, makes sense now, I removed one of method where I save to .json but forgot to do it at loading. Thanks for your help!

**Comment by kuba2k2** [comment]
No problem :smiley:
