### ISSUE TITLE
Internal Server Error -- cannot use library at all

### ISSUE THREAD

**Issue by Kwieeciol** [kapi2289/vulcan-api#93]
The following code worked a few months back
```py
import asyncio
from vulcan import Keystore, Account, Vulcan

# Loading keystore & account
with open("keystore.json") as f:
    keystore = Keystore.load(f)

with open("account.json") as f:
    account = Account.load(f)


async def main():
    # Client creation
    client = Vulcan(keystore=keystore, account=account)
    await client.select_student()  # select the first available student
    print(client.student)
    await client.close()


if __name__ == "__main__":
    asyncio.run(main())
```
When trying to run it now, I get the following error
```py
Traceback (most recent call last):
  File "D:\coding-projects\python\vulcan-marks\main.py", line 21, in <module>
    asyncio.run(main())
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\coding-projects\python\vulcan-marks\main.py", line 16, in main
    await client.select_student()  # select the first available student
  File "D:\coding-projects\python\vulcan-marks\venv\lib\site-packages\vulcan\_client.py", line 42, in select_student
    students = await self.get_students()
  File "D:\coding-projects\python\vulcan-marks\venv\lib\site-packages\vulcan\_client.py", line 61, in get_students
    self._students = await Student.get(self._api)
  File "D:\coding-projects\python\vulcan-marks\venv\lib\site-packages\vulcan\model\_student.py", line 78, in get
    data = await api.get(STUDENT_LIST, **kwargs)
  File "D:\coding-projects\python\vulcan-marks\venv\lib\site-packages\vulcan\_api.py", line 155, in get
    return await self._request("GET", url, body=None, **kwargs)
  File "D:\coding-projects\python\vulcan-marks\venv\lib\site-packages\vulcan\_api.py", line 142, in _request
    raise RuntimeError(status["Message"])
RuntimeError: Internal Server Error (ArgumentException)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000184CA106910>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000184CA0E96A0>, 158185.046)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000184CA106940>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x00000184CA1183D0>
transport: <_ProactorSocketTransport fd=868 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x00000184C8472430>
Traceback (most recent call last):
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\Kwiecinski\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```
I'm really unsure what the issue could be.

**Comment by kuba2k2** [comment]
The following code works perfectly fine for me.

Try registering the keystore again (with a token, symbol and PIN).
If that does not help, provide additional info by enabling debugging:
```py
import logging

client = Vulcan(keystore, account, logging.DEBUG)

# .. rest of the code
```

**Comment by Kwieeciol** [comment]
Yeah there was some issue with the keystore, thanks a lot for the help, have a good day.
